"""initial: bim_elements, parameter_snapshots, qc_findings, users

Revision ID: 09fbee34b117
Revises: 
Create Date: 2026-08-05 23:08:46.840419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fbee34b117'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=128), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('commit_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bim_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bim_elements_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_bim_elements_element_id'), ['element_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bim_elements_level'), ['level'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('parameter_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.String(length=255), nullable=False),
    sa.Column('commit_id', sa.String(length=128), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['bim_elements.element_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parameter_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parameter_snapshots_element_id'), ['element_id'], unique=False)

    op.create_table('qc_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.String(length=255), nullable=False),
    sa.Column('rule', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['bim_elements.element_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qc_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qc_findings_element_id'), ['element_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_findings_element_id'))

    op.drop_table('qc_findings')
    with op.batch_alter_table('parameter_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parameter_snapshots_element_id'))

    op.drop_table('parameter_snapshots')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('bim_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bim_elements_level'))
        batch_op.drop_index(batch_op.f('ix_bim_elements_element_id'))
        batch_op.drop_index(batch_op.f('ix_bim_elements_category'))

    op.drop_table('bim_elements')
    # ### end Alembic commands ###
